# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS@Taipei' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS@Taipei
  pod 'FBSDKCoreKit'  
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKPlacesKit'

  target 'IOS@TaipeiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS@TaipeiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
